import { Song, SongArtist } from '../shared/types';

export const songs: Song[] = [
  {
    id: 1,
    title: "Stronger",
    artist: "Kanye West",
    album: "Graduation",
    genre_ids: [1, 2],
    release_date: "2007-07-31",
    duration: 311,
    explicit: false,
  },
  {
    id: 2,
    title: "HUMBLE.",
    artist: "Kendrick Lamar",
    album: "DAMN.",
    genre_ids: [1],  
    release_date: "2017-03-30",
    duration: 177,
    explicit: true,
  },
  {
    id: 3,
    title: "Nikes",
    artist: "Frank Ocean",
    album: "Blonde",
    genre_ids: [3],
    release_date: "2016-08-20",
    duration: 313,
    explicit: true,
  },
  {
    id: 4,
    title: "Power",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    genre_ids: [1, 4],
    release_date: "2010-07-01",
    duration: 292,
    explicit: true,
  },
  {
    id: 5,
    title: "Swimming Pools (Drank)",
    artist: "Kendrick Lamar",
    album: "good kid, m.A.A.d city",
    genre_ids: [1],  
    release_date: "2012-07-31",
    duration: 235,
    explicit: true,
  },
  {
    id: 6,
    title: "Ivy",
    artist: "Frank Ocean",
    album: "Blonde",
    genre_ids: [3],  
    release_date: "2016-08-20",
    duration: 276,
    explicit: false,
  },
  {
    id: 7,
    title: "All of the Lights",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    genre_ids: [1, 4],
    release_date: "2010-01-18",
    duration: 299,
    explicit: true,
  },
  {
    id: 8,
    title: "Alright",
    artist: "Kendrick Lamar",
    album: "To Pimp a Butterfly",
    genre_ids: [1],
    release_date: "2015-03-15",
    duration: 215,
    explicit: true,
  },
  {
    id: 9,
    title: "Pyramids",
    artist: "Frank Ocean",
    album: "Channel Orange",
    genre_ids: [3],
    release_date: "2012-07-10",
    duration: 598,
    explicit: true,
  }
];

export const songArtists: SongArtist[] = [
  {
    songId: 1,
    artistName: "Kanye West",
    stageName: "Yeezy",
  },
  {
    songId: 2,
    artistName: "Kendrick Lamar",
    stageName: "K. Dot",
  },
  {
    songId: 3,
    artistName: "Frank Ocean",
    stageName: "Lonny Breaux",
  },
];